Set @config in the initializer for RubyEdit::Editor
Why?
- I was getting this error: "undefined method `read' for TTY::File:Module"
  Still not sure what was causing it, but setting @config in the initializer sorted out the issue